# docker compose --env-file .env build distribution
# docker compose --env-file .env up -d
# docker compose logs -f distribution

services:
  distribution:
    build:
      context: ..
      dockerfile: distribution/Dockerfile
      args:
        PROFILE: ${PROFILE:-debug}
        OCI_REGISTRY_PORT: ${OCI_REGISTRY_PORT}
        OCI_REGISTRY_ROOTDIR: ${OCI_REGISTRY_ROOTDIR}
    restart: unless-stopped
    ports:
      - "${OCI_REGISTRY_PORT}:8968"
    volumes:
      - registry_data:${OCI_REGISTRY_ROOTDIR}
    environment:
      PROFILE: ${PROFILE}

      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"

      OCI_REGISTRY_URL: ${OCI_REGISTRY_URL}
      OCI_REGISTRY_PORT: ${OCI_REGISTRY_PORT}
      OCI_REGISTRY_STORAGE: ${OCI_REGISTRY_STORAGE}
      OCI_REGISTRY_ROOTDIR: ${OCI_REGISTRY_ROOTDIR}
      OCI_REGISTRY_PUBLIC_URL: ${OCI_REGISTRY_PUBLIC_URL}

      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFETIME_SECONDS: ${JWT_LIFETIME_SECONDS}
      RUST_LOG: ${RUST_LOG}

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  db_data:
  registry_data:
