[package]
name = "xlinectl"
version = "0.1.0"
edition.workspace = true
authors = ["DatenLord <dev@datenlord.io>"]
repository = "https://github.com/xline-kv/Xline/tree/master/xlinectl"
description = "Command line client for Xline"
license = "Apache-2.0"
readme = "README.md"
categories = ["Client"]
keywords = ["Client", "CommandLine"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
regex = "1.10.5"
serde = { workspace = true }
serde_json = "1.0.125"
shlex = "1.3.0"
tokio = { workspace = true }
tonic = { workspace = true }
utils = { path = "../utils" }
xline-client = { path = "../xline-client" }
xlineapi = { path = "../xlineapi" }

[lints]
workspace = true