on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'project/libcgroups/**'
      - 'project/libcontainer/**'
      - 'project/tools/**'

name: Base Workflow for Check, Build and Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Rustfmt Check
    runs-on: [self-hosted]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt --toolchain nightly

      - name: Run rustfmt
        run: |
          cd project
          cargo +nightly fmt --all --check

  clippy:
    name: Clippy Check
    strategy:
      fail-fast: true

    runs-on: [self-hosted]
    env:
      CARGO_TERM_COLOR: always
      RUSTUP_TOOLCHAIN: stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run cargo clippy
        run: |
          cd project
          cargo clippy --workspace -- -D warnings

  redundancy:
    name: Redundancy Check
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run redundancy check
        run: |
          x=$(find third-party/rust/crates -mindepth 2 -maxdepth 2 -type d -exec bash -c '
            n=$(find "$1" -maxdepth 1 -type f | wc -l)
            [ $n -gt 1 ]
          ' _ {} \; -print -quit | wc -l)
          if [ $x -gt 0 ]; then
            echo "❌ Redundant directories found"
            exit 1
          else
            echo "✅ All good"
            exit 0
          fi

  build:
    name: Buck2 Build

    runs-on: [self-hosted]
    
    env:
      CARGO_TERM_COLOR: always
      RUSTUP_TOOLCHAIN: stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with Buck2
        run: buck2 build //project/...

  test:
    name: Buck2 Test

    runs-on: [self-hosted]
    
    env:
      CARGO_TERM_COLOR: always
      RUSTUP_TOOLCHAIN: stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests
        run: |
          echo "buck2 test"
